const ordersActionTypes = {
    SET_ORDERS_LIST: 'SET_ORDERS_LIST',
    SET_ADDRESS_LIST: 'SET_ADDRESS_LIST',
    SET_PREVIOUS_NODE_FOR_CHANGE_BACKLIGHT: 'SET_PREVIOUS_NODE_FOR_CHANGE_BACKLIGHT',
    SET_CURRENT_ORDER: 'SET_CURRENT_ORDER',
    SET_MAP: 'SET_MAP'
}

export default ordersActionTypes